Volontaria/Website-Volontaria

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
| Type of contribution ?                      | Documentation
| Tickets (_issues_) concerned               | #8 
---
Add github templates:
- Issue template
- PR template
- Contributing file
Standardize contributions and speed-up review
Verification :
> Add issue template, PR template and contributing guidelines files.

- volontaria/src/app/app.module.ts
- volontaria/src/app/components/pages/activities-page/activities-page.component.html
- volontaria/src/app/components/pages/activities-page/activities-page.component.scss
- volontaria/src/app/components/pages/activities-page/activities-page.component.ts
- volontaria/src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.html
- volontaria/src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.scss
- volontaria/src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.ts
| Type of contribution ?                      | [Fix, Features, Documentation, Enhancement]
| Tickets (_issues_) concerned               | #14
---
activities-page
...
-  [ ] I added or modified the attached te
> Activities page and Inscription confirmation page

- src/app/app.component.html
- src/app/app.module.ts
- src/app/components/footer/footer.component.html
- src/app/components/header/header.component.html
- src/app/components/pages/login-page/login-page.component.html
- src/app/components/pages/login-page/login-page.component.scss
- src/app/layouts/default-layout/default-layout.component.spec.ts
- src/app/layouts/default-layout/default-layout.component.ts
- src/app/layouts/login-layout/login-layout.component.spec.ts
- src/app/layouts/login-layout/login-layout.component.ts
- src/assets/scss/_layout.scss
- src/assets/scss/_site.scss
- src/assets/scss/_theme.scss
- src/assets/scss/components/_card.scss
> refactor login design and add layouts

- src/app/app.module.ts
- src/app/components/pages/manage-account-page/manage-account-page.component.ts
- src/app/components/pages/register-activation/register-activation.component.html
- src/app/components/pages/register-activation/register-activation.component.scss
- src/app/components/pages/register-activation/register-activation.component.ts
- src/app/components/pages/register-validation/register-validation.component.html
- src/app/components/pages/register-validation/register-validation.component.scss
- src/app/components/pages/register-validation/register-validation.component.ts
- src/app/services/user.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
| Tickets (_issues_) concerned               | fixed #26 
---
The register flow.
Create a new page of validation when you create a new account (in place of notification)
Create a new page of activation (for when you click in the email)
Verification :
---
**Validation page**
**Activation page (If error with API)**
**Activation page (If success with API)**
**Activation page (During the …
> Feature 26 new register flow

- package-lock.json
- package.json
---
Update the version of `@angular/cli` to fix XSS vulnaribility in `handlebars`
Just change the version in the package.json
> This release contains a single fix to a security vulnerability that was reported for Handlebars. Handlebars was not used during the build process and did not affect any of our users, but the vulnerability was still reported by Github who only check version numbers.
Source : [Release who fix the problem](https://github.com/angular/angular-cli/releases/tag/v1.5.3)
-  [x] My branch name respect the standard defined …
> update angular-cli version

- src/app/components/pages/activities-page/activities-page.component.html
- src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.html
- src/app/components/pages/home-page/home-page.component.html
- src/app/components/pages/myschedule-page/myschedule-page.component.html
| Tickets (_issues_) concerned               | fixed #21 
---
Just the format of date to have full month text
Just change the format in the template PIPE
Seems Angular have already a system of localization we can use. The problem can be solve by changing the process of deployment for the moment.
In the future, IF we want multiple language, we can have a thought about a dynamic localization.
> By default, Angular uses the locale en-US, which is English as spoken in the United States of America.
>
> To set your app's locale to another value, use the CLI parameter --locale with the …
> change date format to long text month

- src/app/services/authentication.service.ts
- src/app/services/globalService.ts
- src/app/services/user.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
---
Allow administrator to change the language of API's error message
Add a settings in the environment files
Add header on all calls of services
> add Accept-Language header and default_language setting

- src/app/components/pages/info-page/info-page.component.html
- src/app/components/pages/info-page/info-page.component.scss
| Tickets (_issues_) concerned               | fixed #37 
---
- Change design of information page
- Update unsubscribe part of info page
- Change `<h2>` to `<h4>`
- Modify SCSS of the page
- Change text as requested
> update desinscription part of info page and design

- src/app/app.module.ts
| Tickets (_issues_) concerned               | fixed #40 
---
Fix an error logged in the console.
Just add a module in the application.
> add BrowserAnimationsModule in the application

- src/app/components/pages/home-page/home-page.component.html
| Tickets (_issues_) concerned               | fixed #42 
---
Fix an error in the console for undefined variable
Add a condition of display
> fix undefined user on homepage init

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/pages/activities-page/activities-page.component.html
- src/app/components/pages/activities-page/activities-page.component.scss
- src/app/components/pages/activities-page/activities-page.component.ts
- src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.ts
- src/app/components/pages/notfound-page/notfound-page.component.spec.ts
- src/app/components/pages/register-activation/register-activation.component.ts
| Tickets (_issues_) concerned               | fixed #23 
---
Upgrade filter to allow user to remove filtering.
Integration of [angular2-multiselect-dropdown](https://cuppalabs.github.io/angular2-multiselect-dropdown/#/singleselection) into the project in place of basic `<select>` html tag with param `multiple`.
---
> refactor filter to use  multiselect dropdown

- src/app/components/pages/manage-account-page/manage-account-page.component.html
---
Change required field to create a new account.
Just refactor the HTML template
> change required field to create an account

- src/app/app.module.ts
- src/app/components/header/header.component.html
- src/app/components/pages/activities-page/activities-page.component.ts
- src/app/components/pages/home-page/home-page.component.html
- src/app/services/event.service.ts
| Tickets (_issues_) concerned               | fixed #50 
---
Filter event by cycle in the `/activities` page in function of the cycle we choosed in the `/index` page.
- Add the http param in the service.
- Refactor `/activities` controller to use new service parameter.
- Refactor some link to use new params or redirect to `/index` in place.
> add filter on listing event in activities page

- src/app/components/pages/contact-page/contact-page.component.scss
- src/app/components/pages/home-page/home-page.component.scss
| Tickets (_issues_) concerned               | fixed #53
---
Fix the display of images on mobile 
Use `max-width` and `min-width` in place of `height`
> fix display of content image

- src/app/components/pages/myschedule-page/myschedule-page.component.html
- src/app/components/pages/myschedule-page/myschedule-page.component.ts
- src/app/services/user.service.ts
| Tickets (_issues_) concerned               | https://genielibre.com/issues/26
---
Allow user to change his password from his profile
Add a new button to change password in the profile page
Create a new modal form
Add some validators
**Example with multiple error**
> add change password form

- src/app/components/pages/home-page/home-page.component.html
| Tickets (_issues_) concerned               | https://genielibre.com/issues/59
---
Added a plural condition on a text of the homepage
simply added a condition
> Add plural condition on homepage text

- src/app/components/pages/activities-page/activities-page.component.ts
| Tickets (_issues_) concerned               | [68](https://genielibre.com/issues/68)
---
The text of the filter in the Participation page
-  [X] I added or modified the attached tests
> Change the filter names to help the users

- src/app/components/pages/info-page/info-page.component.html
- src/app/components/pages/info-page/info-page.component.scss
- src/assets/scss/_site.scss
- src/assets/scss/_theme.scss
- src/assets/scss/app.scss
- src/assets/scss/components/_alert.scss
| Tickets (_issues_) concerned               | [65](https://genielibre.com/issues/65)
---
Change the content on the information page with new text given by NousRire
- Add a new `alert` component
- Change the content
- Refactor title architecture to use CSS counter on title
> change info page content

- package-lock.json
- package.json
- src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.html
- src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.ts
- src/assets/scss/components/_button.scss
- src/assets/scss/components/forms/_input.scss
| Tickets (_issues_) concerned               | [79](https://genielibre.com/issues/79)
---
Add a verification when user apply to an event to check if the user has read the info page.
- Add a checkbox on the verification page (with link to the info page)
- Add a new design for disabled button
- Add condition on verification button 
> add checkbox to read info page when apply to event

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/my-modal/my-modal.component.html
- src/app/components/my-modal/my-modal.component.scss
- src/app/components/my-modal/my-modal.component.ts
- src/app/components/pages/admin-cell/admin-cell.component.html
- src/app/components/pages/admin-cell/admin-cell.component.scss
- src/app/components/pages/admin-cell/admin-cell.component.ts
- src/app/components/pages/admin-cycles/admin-cycles.component.html
- src/app/components/pages/admin-cycles/admin-cycles.component.ts
- src/app/services/event.service.ts
- src/assets/scss/_theme.scss
- src/assets/scss/components/_alert.scss
- src/assets/scss/components/forms/_input.scss
- src/assets/scss/components/forms/_select.scss
- src/styles.scss
| Tickets (_issues_) concerned               | https://genielibre.com/issues/51
---
- Add the possibility to create an event from the cell page
- Add the button with check of the right to display it.
- Add a modal with the form to create a event inside.
- Fix un z-index error for the modal
- Use [Pick datetime](https://www.npmjs.com/package/ng-pick-datetime) for the date
- Fix overlay of modal
- Fix display of modal vs angular2-multiselect
- Fix display modal in case of modal bigger than screen
-  [x] This …
> Add event creation

- src/app/app.module.ts
- src/app/components/pages/forgot-password-confirmation/forgot-password-confirmation.component.html
- src/app/components/pages/forgot-password-confirmation/forgot-password-confirmation.component.scss
- src/app/components/pages/forgot-password-confirmation/forgot-password-confirmation.component.ts
- src/app/components/pages/forgot-password/forgot-password.component.html
- src/app/components/pages/forgot-password/forgot-password.component.scss
- src/app/components/pages/forgot-password/forgot-password.component.ts
- src/app/components/pages/login-page/login-page.component.html
- src/app/components/pages/reset-password/reset-password.component.html
- src/app/components/pages/reset-password/reset-password.component.scss
- src/app/components/pages/reset-password/reset-password.component.ts
- src/app/layouts/login-layout/login-layout.component.scss
- src/app/layouts/login-layout/login-layout.component.ts
- src/app/services/authentication.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
| Tickets (_issues_) concerned               | [56](https://genielibre.com/issues/56)
---
Allow user to reset his password if forgot.
- Add a link on login page.
- Add a form to retrieve an account with a username
- Allow user to change password with a token to change his password
> add forgot password feature

- src/app/components/pages/login-page/login-page.component.html
| Tickets (_issues_) concerned               | [[82](https://genielibre.com/issues/82)]
---
removed the intro screen msg box
> Remove login message box

- src/app/app.module.ts
- src/app/components/header/header.component.html
- src/app/directives/permission.directive.ts
---
Change visibility condition in topnav
Use `IsAuthenticated()` function of authenticate service.
> fix item top nav visibility

- package.json
- src/app/app.module.ts
- src/app/components/my-table/my-table.component.html
- src/app/components/my-table/my-table.component.scss
- src/app/components/my-table/my-table.component.ts
- src/app/components/pages/activities-page/activities-page.component.html
- src/app/components/pages/activities-page/activities-page.component.ts
- src/app/components/pages/home-page/home-page.component.html
- src/app/components/pages/home-page/home-page.component.scss
- src/app/components/pages/home-page/home-page.component.ts
- src/assets/scss/_theme.scss
| Tickets (_issues_) concerned               | [73](https://genielibre.com/issues/73)
---
Change flow to filter by `cell` in place of `cycle` in the home page
- Add a new `my-table` component
- Display all cell in a `my-table` in place of the list of cycle
- Change activities page to get events by cell in place of cycle
- Refactor filter on the activities page to allow user to filter by cycle if he want (in place of cell because is already pre-filtered)
-  [x] This Pull-Request fully meets the requirements …
> Enhancement change inscription flow

- src/app/components/pages/activities-page/activity-confirmation-page/activity-confirmation-page.component.html
- src/app/components/pages/home-page/home-page.component.html
- src/app/components/pages/login-page/login-page.component.html
| Tickets (_issues_) concerned               | [[91]](https://genielibre.com/issues/91)
---
Some small text changes
> Text changes requests

- src/app/components/pages/admin-event/admin-event.component.ts
| Tickets (_issues_) concerned               | [[94]](https://genielibre.com/issues/94)
---
Added a column for the mobile phone in the Event admin section
> Add a column for the mobile phone number in the Event section

- src/app/components/pages/admin-cells/admin-cells.component.ts
- src/app/components/pages/home-page/home-page.component.ts
- src/app/services/cell.service.ts
| Tickets (_issues_) concerned               | [[93]](https://genielibre.com/issues/93)
---
Added an option to have the listing of the cell ordered by the cell name
> Get the option to have a listing of the cells ordered by name

- src/app/components/my-table/my-table.component.html
- src/app/components/my-table/my-table.component.scss
- src/app/components/my-table/my-table.component.ts
- src/app/components/pages/admin-volunteers/admin-volunteers.component.html
- src/app/components/pages/admin-volunteers/admin-volunteers.component.ts
- src/app/services/user.service.ts
---
Add pagination on user admin panel
Add loading image when my-table have no data
Refactor `my-table` component to manage pagination and loading image
Refactor users list in admin panel to use the new pagination system
Refactor users service to manage pagination HttpParam and other one like filters and ordering
> Feature add pagination on table

- src/app/components/header/header.component.html
| Tickets (_issues_) concerned               | [[212]](https://genielibre.com/issues/212)
---
Add a s to information in menu
> Need to add a s to information in menu

- src/app/components/pages/admin-cycles/admin-cycles.component.ts
| Tickets (_issues_) concerned               | [[211]](https://genielibre.com/issues/211)
---
Change the settings of the button to by relatif to the fact that the user is a super user or not 
> Create cycle btn only available to superuser

- src/app/components/pages/contact-page/contact-page.component.html
| Tickets (_issues_) concerned               | [[213]](https://genielibre.com/issues/213)
---
Removed Sébastien from contact page
> Remove Sébastien from contact page

- src/app/components/pages/login-page/login-page.component.html
- src/assets/scss/components/_card.scss
| Tickets (_issues_) concerned               | [[132]](https://genielibre.com/issues/132)
---
Added some text on the login page
> Add text with login information on the login page

- INSTALL.md
| Type of contribution ?                      | Documentation
---
Update the deprecated install documentation of the project
Just changed the content of the `INSTALL.md` file
Add a line about the fact we need to install the API to be up and running
> update install documentation

- src/app/components/pages/admin-volunteers/admin-volunteers.component.html
- src/app/components/pages/admin-volunteers/admin-volunteers.component.ts
- src/app/services/user.service.ts
| Tickets (_issues_) concerned               | [[221]](https://genielibre.com/issues/221)
---
Fetching the admin volunteer list section from the api with a search param
-  [X] I added or modified the attached tests
> Filtering the admin volunteer list section with paging

- src/app/components/pages/contact-page/contact-page.component.html
- src/app/components/pages/info-page/info-page.component.html
| Tickets (_issues_) concerned               | [[243]](https://genielibre.com/issues/243)
---
Text in contact page and information page
-  [X] I added or modified the attached tests
> Update contact and info page
